### ISSUE TITLE
License

### ISSUE THREAD

**Issue by zombie-einstein** [jeremiecoullon/jax-tqdm#14]
@jeremiecoullon just noticed we don't have an open source license on this. Worth adding one? If so any opinions on what to use?

**Comment by jeremiecoullon** [comment]
I don't have strong opinions about which one, but I think 2 [standard ones people use](https://blog.zenhub.com/the-5-best-open-source-licenses-for-securing-your-software-rights/) are apache (like [here](https://github.com/jeremiecoullon/SGMCMCJax/blob/master/LICENSE)): you can use the software to do [whatever you want](https://www.mend.io/blog/top-10-apache-license-questions-answered/), or MIT (you can apparently also do what you want with the code).

do you have any preferences?

**Comment by zombie-einstein** [comment]
Not a strong one but usually go MIT? I can add the file later if we're happy with that?

**Comment by zombie-einstein** [comment]
In fact looking at the project file with have listed as MIT, but I guess we just didn't add the actual file

**Comment by jeremiecoullon** [comment]
Ok for using MIT!
