### ISSUE TITLE
jax callback change break tqdm updates

### ISSUE THREAD

**Issue by mdmould** [jeremiecoullon/jax-tqdm#19]
As of jax 0.4.27, arguments to `jax.debug.callback` are now `jax.Array` rather than `np.ndarray` (see https://jax.readthedocs.io/en/latest/changelog.html#jax-0-4-27-may-7-2024).

This break the tqdm updates with error `TypeError: unsupported type for timedelta seconds component: jaxlib.xla_extension.ArrayImpl`.

It looks like the fix would be to use `jax.tree.map(np.asarray, args)` on the callback args.

**Comment by zombie-einstein** [comment]
Closing as now fixed in latest release
